### ISSUE TITLE
Both docs and tests indicate BreadcrumbData type should have string possibility for breadcrumb field

### ISSUE THREAD

**Issue by cp3p0** [icd2k3/use-react-router-breadcrumbs#60]
Super confused and could use some assistance, am trying to use the breadcrumbs hook as described in both the documentation and the test suite and I have code like:

```javascript
const breadcrumbs = useBreadcrumbs(flattenedRoutes);
// where flattened routes looks like [{ path: '/somepath', breadcrumb: 'My Heading' }]
```
but when I inspect breadcrumbs in debug mode `breadcrumb` is clearly not a string as expected, it's rendering it into a ReactNode

(index 1, since 0 is home, but home is also a react span)
```
breadcrumb:
  $$typeof: Symbol(react.element)
  key: "/somepath"
  props: {children: 'My Heading'}
  ref: null
  type: "span"
```

Which looks right based on the typings but not according to the docs/tests... if someone could illuminate that'd be great 😅

https://github.com/icd2k3/use-react-router-breadcrumbs/blob/2cbfce211439e2d48e97a86f031ea01580ec24ab/src/index.tsx#L80
